"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%id3b+j0z7wypw6g7qcqc5=j%25n65%7+26wppkk@-c7a922$m"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = ["backend-api", "localhost"]

ALLOWED_HOSTS = ["backend-api", "localhost", "127.0.0.1", "[::1]"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "APIs",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware debe ir lo más arriba posible
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es-mx"

TIME_ZONE = "America/Mexico_City"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

# ── Emulador de Apigee ──────────────────────────────────────────────
# API de administración del emulador (puerto 8080 del contenedor apigee-dev).
# Es la misma que usa la extensión Cloud Code de VS Code para desplegar.
APIGEE_EMULATOR_URL = os.environ.get("APIGEE_EMULATOR_URL", "http://apigee-dev:8080")

# Environment activo dentro del emulador (carpeta en src/main/apigee/environments).
APIGEE_ENVIRONMENT = os.environ.get("APIGEE_ENVIRONMENT", "apigee-dev")

# Raíz del workspace montado desde el host: la carpeta 'src' del repositorio.
APIGEE_SOURCE_ROOT = os.environ.get("APIGEE_SOURCE_ROOT", "/app/workspace")

# Prefijo con el que el emulador espera encontrar las rutas dentro del ZIP.
APIGEE_SOURCE_ARCHIVE_PREFIX = "src"

# Compilar y activar un contrato puede tardar varios segundos.
APIGEE_EMULATOR_TIMEOUT = int(os.environ.get("APIGEE_EMULATOR_TIMEOUT", "120"))

# Runtime del emulador: el puerto por el que entra el tráfico de los proxies.
# La barra "Send Requests" de la traza lo usa para lanzar peticiones desde la UI.
APIGEE_RUNTIME_URL = os.environ.get("APIGEE_RUNTIME_URL", "http://apigee-dev:8998")
APIGEE_RUNTIME_TIMEOUT = int(os.environ.get("APIGEE_RUNTIME_TIMEOUT", "30"))

# Cada cuánto sondea el backend al emulador mientras hay un stream de trace
# abierto. El emulador no notifica nada por su cuenta: solo expone el GET.
APIGEE_TRACE_POLL_SECONDS = float(os.environ.get("APIGEE_TRACE_POLL_SECONDS", "1.0"))

# Tope de vida de un stream SSE, para que un cliente que se va no deje el hilo
# del servidor de desarrollo ocupado indefinidamente.
APIGEE_TRACE_STREAM_MAX_SECONDS = int(
    os.environ.get("APIGEE_TRACE_STREAM_MAX_SECONDS", "660")
)

# Los bundles de proxy se suben completos en memoria (por defecto DRF corta en 2.5 MB).
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Apigee Local Custom Dashboard API",
    "DESCRIPTION": "Ecosistema de aceleración para desarrollo local en Apigee",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # Cambia a 'DEBUG' para ver todo el detalle
    },
}
