version: '3.8'

# Definimos el volumen compartido
volumes:
  apigee_contracts_vol:

services:
  apigee-emulator:
    image: gcr.io/apigee-release/hybrid/apigee-emulator:1.15.2
    container_name: apigee-dev
    ports:
      - "8999:8080"
      - "8445:8998"
    environment:
      - TZ=America/Mexico_City
      - APIGEE_USER=test
      - APIGEE_PASSWORD=test
    volumes:
      # Montamos /opt/apigee del emulador hacia el volumen compartido
      - apigee_contracts_vol:/opt/apigee
    restart: always

  fake-management-api:
    build: ./backend # Asegúrate de que esto apunte a donde está tu Dockerfile de Flask
    container_name: apigee-fake-control-plane
    ports:
      - "8446:8446"
    environment:
      - TZ=America/Mexico_City
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - ./backend:/app
      - apigee_contracts_vol:/apigee_runtime
    depends_on:
      - apigee-emulator
    restart: always